# Generated by Django 4.2.4 on 2023-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(REGULAR)', 'CSE(R)'), ('CSE(HONOURS)', 'CSE(H)'), ('CSIT', 'CSIT')], max_length=100),
        ),
    ]
