# Generated by Django 4.2.4 on 2023-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_course_semester_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], default='BTECH', max_length=50),
            preserve_default=False,
        ),
    ]
